### ISSUE TITLE
unable to open file with double click on ntfs partition

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [notepadqq/notepadqq#185]
On a NTFS partition, all files have **-rwxrwxrwx 1 root root**. With Files configured to "Run executable text files when they are opened", I am unable to double click opening any text file in notepadqq because all files are executable and there is no way to remove x permission on NTFS for a particular file (at least I don't know how). Is there a workaround other than changing it to "View executable text files when they are opened"?

![notepadqq as default for text/plain](http://i.imgur.com/0tH8cNBl.png)

![but the file permission always has x on ntfs](http://i.imgur.com/GdKKPTcl.png)

I can still open the file in notepadqq by right clock -> open with -> other. It's just inconvenient.

**Comment by darealshinji** [comment]
I think this issue is related to your file brower (Nautilus?) and not to NQQ itself. A workaround solution might be to install another file browser, set that one to always view executable text file and use that file browser to navigate NTFS file systems. You could try that with Nemo, which is a fork of Nautilus and not much different.

**Comment by danieleds** [comment]
I agree. Closing.
