### ISSUE TITLE
Regex capturing groups and backreferences don't seem to work

### ISSUE THREAD

**Issue by Swyter** [notepadqq/notepadqq#191]
I tend to use a lot of regular expressions for quickly editing text so I noticed that opening the _Search and replace_ dialog with Ctrl + H, switching to _Search with regular expressions_ and using capture groups with references doesn't seem to work at all.

In Notepad you can use something like `(a-z)+` as search string and then use Perl-style back-references (`\1` in older versions and `$1` since v6.0) in the replacement input box to get the capture result.

In Notepadqq the regular expressions seem to work fine, but they get replaced by literals (like `$1`), so they are useless.

---
- http://www.rexegg.com/regex-capture.html
- https://notepad-plus-plus.org/news/notepad-6.0-release.html
- http://stackoverflow.com/questions/11970405/
- http://stackoverflow.com/questions/2890700/
- http://stackoverflow.com/questions/17998179/

**Comment by Algomorph** [comment]
Bump

**Comment by danieleds** [comment]
If someone is willing to work on this, I can provide help as needed.

Thanks for the report.

**Comment by Algomorph** [comment]
@danieleds Can you give us a brief on
1) What source files would we need to look at
2) In general terms, what would need to be changed
I might do it if I find that it takes a reasonable amount of time, I need your input to estimate. Thanks in advance.

**Comment by danieleds** [comment]
The replace dialog is located at `src/ui/Search/frmsearchreplace.cpp`. The "replace" command constructs an object containing information relative to the action and sends it to the Editor (see method `frmSearchReplace::replace()`). In this case, the message is `C_FUN_REPLACE`.

By opening `src/editor/app.js` and searching for `C_FUN_REPLACE` you will find the handler for the replace command. You'll see that the documentation states:

> Replace the currently selected text, then search with a specified regex (calls C_FUN_SEARCH)

so the best thing to do would be to take a look at the search handler and:

  1. see how to obtain captured groups from CodeMirror. [[manual]](https://codemirror.net/doc/manual.html)
  2. cache them so that they can be used in the following "replace" command, if any.

It should be fairly simple, the only obstacle might be CodeMirror. Worst case scenario: a patch to `search/searchcursor.js` in CodeMirror is needed.

Let me know for any kind of doubt :-)

**Comment by Algomorph** [comment]
It took me three whole hours... My fault though, mostly, for not having an appropriate JavaScript IDE and being rusty on JavaScript...

**Comment by snarum-NIS** [comment]
This still doesn't seem to work correctly to me.  Using the normal search dialog, the following regex doesn't find any matches.  Using the advanced search dialog, it finds matches but won't replace with the backreferences.

Search: (\w+)\:(\s+)$
Replace: useradd -n -g $2 $1 <etc>

File contents:
user1:1000
user2:1001
user3:1010
user4:1003
<etc>

Advanced search dialog replace ends up with:
useradd -n -g $2 $1 <etc>
useradd -n -g $2 $1 <etc>
useradd -n -g $2 $1 <etc>
useradd -n -g $2 $1 <etc>
<etc>

  I also tried using \2 \1 in the replace string and resulted in:

useradd -n -g \2 \1 <etc>
useradd -n -g \2 \1 <etc>
useradd -n -g \2 \1 <etc>
useradd -n -g \2 \1 <etc>
<etc>

  In both dialogs, the use regex box was ticked.

**Comment by JuBan1** [comment]
Yep, backreferences aren't supported.

**Comment by JuBan1** [comment]
Fixed in #570. The syntax to refer to back references is `\x` with `x` being a digit.
