### ISSUE TITLE
PPA not working for Debian

### ISSUE THREAD

**Issue by ArcaneEngineer** [notepadqq/notepadqq#221]
Under Debian 8 Jessie, installing via .deb is a mission as there are a bunch of unresolved dependencies I don't wish to clutter my system with. So I tried grabbing from PPA but on `sudo apt-get update` I get:

W: Failed to fetch http://ppa.launchpad.net/xorg-edgers/ppa/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xorg-edgers/ppa/ubuntu/dists/jessie/main/binary-i386/Packages  404  Not Found

...I notice if I replace "jessie" in there with say "xenial" in a browser, the URL no longer gives 404. Not sure how to actually make that work for me, however, using `apt-get update`.

Is there any simple way to get notepadqq for debian via ppa?

**Comment by guekho64** [comment]
?

PPA working for me under Deepin 15.1.1 (Debian Jessie)

Try using "Trusty" as the main dist for the PPA.

Remember that **PPA's in general AREN'T MEANT FOR DEBIAN**, just for Ubuntu.

Rarely a PPA has support for a Debian Codename...

In fact, Launchpad (PPA's Home) was made by Canonical.

_If you use "jessie", "wheezy" or any other codename from a Debian release, it'll throw an error because 
it doesn't exist in the "dists" folder from the PPA._

**Even some PPA's throw an error when setting "Xenial" as the main PPA distro, because the main PPA maintainer haven't been there for a while, and as consequence, the PPA isn't updated, so it won't recognize "Xenial" as an Ubuntu Codename**

If you don't know how to "See" if the PPA has support for an specifical codename, try to enter the PPA's URL in a browser  and add **"/dists" at the end.**

Example:

PPA => http://ppa.launchpad.net/no1wantdthisname/openjdk-fontfix/ubuntu/

Once you add "/dists" at the end:

http://ppa.launchpad.net/no1wantdthisname/openjdk-fontfix/ubuntu/**dists/**


Once you get there you will be able to see what "Codenames" are supported by the PPA and then you can modify your APT source file to match the codename of your choice

deb http://ppa.launchpad.net/no1wantdthisname/openjdk-fontfix/ubuntu **"Codename In Lowercase"** main

PD: I recommend "Trusty" as the codename, because not all PPA's have been updated recently, so maybe it will cause some troubles if you use "Xenial"

**Comment by ArcaneEngineer** [comment]
@guekho64 Thanks... the key was "and then you can modify your APT source file to match the codename of your choice"... last night I could not find notepadqq in `/etc/apt/source.list` after adding the PPA; instead it was in `/etc/apt/sources.list.d/`. I have learned something new about Debian. :)
