### ISSUE TITLE
Find in files is painfully slow

### ISSUE THREAD

**Issue by ericjs** [notepadqq/notepadqq#227]
A search (plain text, recursive directories) that took less than 10 seconds in Kate took nearly  3 minutes. (using v0.51.0)

**Comment by Teklad** [comment]
Could you give an example as to what kind of files are in the directories?  I have a pretty good idea of what the issue might be but I want to be sure.  Mainly I'm curious if there are a lot of binary files mixed in with the text files.

**Comment by ericjs** [comment]
Sorry, I no longer recall what the search it was that I tested. But I'm happy to try more searches, and try both ones the do and don't fit your theory.

**Comment by Teklad** [comment]
I've looked into this issue more lately and it appears the way Kate handles file searching is far superior to how we are currently doing it.

Once I get some spare time I'll see about redesigning it based around kate's internal design(threading, file path handling, etc.), so long as nobody has any objections.

**Comment by danieleds** [comment]
Sounds good! This feature was coded in a bit of a rush and I'm sure there's plenty of room for improvement.

I suggest you provide a small report of the work you're going to do, so that we can discuss it before you start working on it.

**Comment by Teklad** [comment]
So I've done a little experimenting here... it mostly looks like the way we are iterating with the regex matching is inefficient.

I've got a fully working variant that can blast through it in no time.... but I noticed a few things.

I think it would be best to separate out the file searching function out into their own functions.  This will keep the code clean and make it a lot easier to make changes to just the portions that search within the files without bothering anything else.

We could then just pass a pointer like so:
`void SearchRegex(const QString &fileName, const QString &content)`

Alternatively the file could be opened within the regex function, not really sure how I want to go about it yet.

That should at least put us in the right direction.  I've already revised the internal regex code here locally to work similar to kate.  There's already a large speed improvement.

One thing I've noticed is the memory usage for notepadqq jumps dramatically when using "Find in Files" on directories with lots of large files.  Binary files absolutely destroy its speed.

After some testing it appears buildResult() is the culprit.  When it runs into files with really long lines it slows down the search dramatically, as well as ramps up the memory usage quite a bit + maxing one of my cores.

It would probably be better to have buildResult work off of values given to it rather than composing massive portions of text within it.  Passing line,column and a few other things should allow pulling the information it needs with a lot less strain.  Having a maximum cut-off for preview length probably wouldn't hurt either.

On a side note, I was wondering if decodeText has any facilities to just decode a string... it would probably be best to do regex line-by-line for the most part unless a multi-line regex is detected.

That's what I got so far on the subject.  Let me know what you think.

**Comment by ericjs** [comment]
It's great to read about the great progress! I wonder if it would make sense for the app to have some notion of text vs binary files (it seems to me I've encountered this in the past in some editors I've used), with some default list of types that the user can add to (perhaps using the system's notion of mime type?) such that binary files could be excluded from the search. As a use case I often want to search across large swaths of my source code tree which includes both source files, the binary compiled units from those files, binary resources, etc. and in such cases searching the binary files in not useful.

**Comment by danieleds** [comment]
@Teklad sounds good! :+1: 

@ericjs to exclude binary files, have you tried using the filters? That's how most text editors do :)

**Comment by ericjs** [comment]
I assume you mean the inclusive filename pattern filters? I generally do use those. But there's a half a dozen or more extensions of text source / configuration / resource files  in many of the projects I work on. most of the time I know one or two partiular types I want to search, but now and then I want a broader search and it can be a pain to remember what all relevant extensions needed. 

Being able to exclude binaries wholesale is not a "must-have" feature but it could be useful at times, and I thought being able to exclude binary files might benefit the search algorithm.

**Comment by Teklad** [comment]
Just wanted to get a bit of advice here.  From what I can tell kate's SearchDiskFiles.cpp/.h is completely disconnected from the main kate program, which makes it easily portable to other projects.

It is currently licensed under the same license as notepadqq.  kate's search functions are insanely fast for file operations.

It might be best to incorporate the plugin into notepadqq and hook it appropriately rather than reinventing the wheel here.  It would save a lot of time and bring about a fairly nice performance improvement to boot.  A bonus being it'll give me more time to work on other features/bugs. :P 

I should probably mention that QT does have mimetype support... it'd be easy to go ahead and add an option to "include binary files in search"... defaulting unchecked perhaps?

Just wanting to gather thoughts on all this before I go hammering away needlessly.

**Comment by ericjs** [comment]
If I'm not mistaken that file search is a Kate "plug-in". Is it worth considering making notepadqq support Kate plugins generally? (No opinion here, just tossing the idea out there.)

This may not be relevant as the UI tie-in might be entirely separate, but one of the things about Kate's search that drives me crazy is that unlike any other editor I've used, it is tied to the document window. So if you do a search then switch to a different open document, the search panel has whatever was in the fields last time you searched from that document, not that search you just did from the other document. Most of the time this is contrary to what I want, though I have to admit every once in a while it is handy to be able to have 2 different searches active in 2 different document...

**Comment by Teklad** [comment]
The main difference between how we do it and how they do it is more or 
less the entire GUI and backend for searching is built as a plugin.  
Currently, we don't have that type of plugin support built-in.

I'm pretty sure some of kate's plugins probably use KDE libs too, which 
isn't something I would want to cram into an editor that's supposed to 
be light.  I don't see a problem with implementing this particular 
feature though, since it only uses QT's implementation.

The goal of this particular issue is to implement better file searching 
with as little overhead as possible.  I'm not sure if a "plugin" type 
system for core editor features would be a good way to go.  An editor 
without much in the way of search features wouldn't be very useful to me. :P

As you guessed, the user interface is separated from the backend side 
where the searching actually happens, so those issues you have with kate 
wouldn't show up in this case.  I intend to rip out the backend and use 
it for our purposes, since kate's file searching is very mature compared 
to our own.

**Comment by Teklad** [comment]
Okay... so I have an initial implementation up... I'm still sorting out the details.  It looks promising so far though.  Speed is now similar to kate.  Currently only single line regex is supported... working on adapting the multi-line regex now.

I was tempted to rip out the search feature entirely and start from scratch... but the amount of time needed for a complete overhaul is a little more than I have available right now.  These improvements will keep performance at a very nice level for the time being.

Eventually when other things are finished I'd like to revisit this issue and see about some cleanup/refactoring.  Maybe using signals to tell the GUI to add results on the fly instead of building a list in memory then applying it.

If you want to give it a try, just clone my repository and give the search-overhaul branch a go.  The code is still a work in progress but the speed improvements are there.

**Comment by Teklad** [comment]
Just adding the finishing touches to the new "Search In Files" performance improvements.  Should have a patch very soon to get this issue resolved. :)

**Comment by danieleds** [comment]
PR number is #256

**Comment by danieleds** [comment]
Fixed.
