### ISSUE TITLE
Editor focus is not correct on start

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#265]
This is evident after @JuBan1 's PR #249 which added session support (but the issue isn't caused by that).

I'm trying to understand what's going on.
##

**Comment by Teklad** [comment]
Putting currentEditor()->setFocus() at the end of loadSession forced it to focus properly for me.  Of course there may be a better place to put it.

The way it was setup appears to favor focusing the very last tab instead, which is impossible when its not displayed on initial startup. :P

**Comment by danieleds** [comment]
Yes, that's a different issue, I noticed that too. Your fix is correct.

However the problem discussed here is different: see here https://github.com/notepadqq/notepadqq/pull/249#issuecomment-245045728

The problem, I believe, is located among TopEditorContainer, EditorTabWidget and maybe the JS script (unlikely). We shouldn't need to apply the focus manually to fix things. It should just work.

**Comment by severach** [comment]
I'd like to expand this with tabs.

Open 4 tabs in noteqpadqq.
Select the first tab.
Close notepadqq.
Open notepadqq.
Press Up or Down. These keys do nothing because the editor does not have the focus.
What has the focus? Press left/right. The tab bar has the focus.
Press tab a few times and the focus lands in the editor.

There's more.
Select the first tab.
Close and open notepadqq.
Click on each tab with the mouse. Focus is outside the editor in tabs 1,2,3. The editor has the focus in the last tab 4.
Click through each tab setting the focus to the editor.
Click through each tab again and the focus will still be in the editor.
