### ISSUE TITLE
"Run" menu

### ISSUE THREAD

**Issue by danieleds** [notepadqq/notepadqq#279]
The "Run" menu is only partially implemented.
- "Run -> Run...": needs to be implemented
  - it allows to run commands on the fly, and optionally to save them
- "Run -> Modify Shortcut": we might not need this, we already have a general shortcut management.
- "Run -> Modify Commands": needs to be implemented.
  - it allows to add, edit or delete custom commands. It would be nice to be able to specify special tokens in the launch string... e.g. `%filename` for the filename, or `%selection`, or `%path`, etc.
##

**Comment by Teklad** [comment]
I know that in Notepad++, they have a dialog separate from the preferences menu where you can do this.  Would it be okay to make it part of the preferences menu and to just display the proper tab when clicking "Modify run commands"?  Basically just make it a sub-section in preferences rather than separating it.

I have a pretty good implementation idea in my head so I'd like to take a crack at this.

**Comment by danieleds** [comment]
I'd prefer to keep them separate. They're not really "settings".

**Comment by Teklad** [comment]
Alright, could you assign this to me?  I should be able to get a working implementation pretty quickly.  It's a simple feature to implement.

**Comment by danieleds** [comment]
Sure!

**Comment by danieleds** [comment]
Implemented with PR #289
