### ISSUE TITLE
Bring to front when launching from Files

### ISSUE THREAD

**Issue by nickcodefresh** [notepadqq/notepadqq#310]
Is there anyway to bring notepadqq to the front when I open a file by double clicking it in Files? At the moment the icon in the Ubunto launcher just flashes.

thanks

Nick

**Comment by JuBan1** [comment]
I believe this isn't Nqq's fault but the window manager's focus stealing prevention at work. Basically Ubuntu doesn't let Nqq pop up because it thinks you're currently at workin Files and doesn't want anything to interrupt that.

I don't know if we can programatically work around that but you can try the following fix to disable focus prevention: http://askubuntu.com/questions/128738/when-i-launch-an-app-the-focus-doesnt-move-to-the-opened-app

**Comment by danieleds** [comment]
I've tried a workaround, does it work for you?  e7f426469714bc374490dd9f7bde70dab0396227

I get an odd behavior with non-maximized windows (they move a little bit to the top each time I open a file), I'm not sure if it is a problem with my DE or with Qt in general.

**Comment by nickcodefresh** [comment]
thanks it works for me!
