### ISSUE TITLE
QtWebEngine: Language injection.

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#380]
The way we currently have languages setup was either to wait for QWebEngine(previous), or use QML(current).  I propose we make a LangData.json file and inject the languages into the javascript on the fly.... this has the benefit of both getting rid of the QML dependency and giving us a solid reliable method for getting languages data.

It would use QJsonDocument to parse the json text and import the languages to our UI.... after which we could export the converted data to our settings(or possibly another settings file)... in its converted format to speed up Notepadqq for when it gets started the next time.

Thoughts on this @danieleds or @JuBan1 .... or both :P?  I already turned this.languages in Languages.js into a json file, so it wouldn't take long to implement.

**Comment by JuBan1** [comment]
Wouldn't this even make adding new languages for users easier? It's simpler to change a JSON file rather than a JavaScript code piece. Plus, better performance. I don't see why not.

**Comment by Teklad** [comment]
Yea... that's the point... with enough tweaking it should allow users to add their own languages without the need to do really hacky things. :P

**Comment by Teklad** [comment]
I was thinking ~/.config/langs.json ... we would store a hash of that in our settings... and only update our cache when the hash changes.

We could have an autoload directory which Notepadqq would browse and import *.js files for user-defined languages.

**Comment by danieleds** [comment]
A lot better than our current solution! I like especially the possibility for advanced users to install custom languages, which is requested from time to time.

But let's keep this out from the QtWebEngine changeset for now... let's try to include only the essential changes. There's time for these optimizations later :) The PR is already huge!

I expect to merge the PR in a temporary qwebengine branch, then keep testing and fixing things for a while and then merge into master, after moving the QtWebKit version in another branch so that we can still support it.

I need to know when you think the initial switch to QtWebEngine is ready and stable enough to be merged, so that we can clean everything and focus on the minor stuff.

**Comment by Teklad** [comment]
Well, I'm being nitpicky at the moment.  I'm mainly working on 
performance improvements and bug fixes at this point since most of the 
features are back to working again... on a side note... I just gained 
some massive startup times by enqueuing messages in JsProxy until the JS 
side is ready to receive data.

This change almost completely gets rid of QEventLoop blocking, except 
for when we do a C_FUN_GET_VALUE(Sessions are important)... I've 
impressed myself. :X

**Comment by JuBan1** [comment]
On that note: right now all <language>.js files are hard-coded into app.js and get loaded no matter what.

It would probably shave off a nice bit of memory footprint and loading time if we could only load the correct <language>.js file on-demand. And it would get rid of a bunch of these error messages mentioned in the opening post since the languages would simply not get loaded.

I tried replicating `setTheme`'s way of doing this: adding an empty `<script>` tab and setting its `src` when `setLanguage()` is called. That works but the <language>.js files usually contain some on-load function that is supposed to be executed when the file is loaded. Programmatically setting the `<script>`'s `src` attribute doesn't trigger that behavior. 

Here's why my lack of knowledge of JS bites me. I don't know how to explicitly execute the on-load stuff myself. I tried `eval( <language>.js )` but that throws a syntax error.

**Comment by Teklad** [comment]
I recommend looking into QWebEngineScripts for a more elegant solution on
doing that. It allows more fine grained control over JavaScript injection
and such.  Definitely something worth looking into considering we load
every dang mode we have available at the moment... Which I'm sure eats a
decent bit of memory.
