### ISSUE TITLE
QtWebEngine: Possible memory leak

### ISSUE THREAD

**Issue by JuBan1** [notepadqq/notepadqq#388]
Right now the QtWebEngine branch leaks a decent amount of memory.

To replicate:
* Open your favorite system monitor and watch notepadqq-bin's memory usage.
* Open and close tabs a bunch of times.
* Watch memory grow and not shrink again.

After 60 open/closed tabs memory consumption grew from ~120MiB to ~320MiB for me. That's around 3MiB per opened tab.

Not sure where it originates from. The `CustomQWebView`, `JsProxy` and `Editor` objects are properly destroyed when a tab is closed. Valgrind crashes the process for some reason, so I can't really trace it.

This may not be a memory leak but some lazy block deallocation from somewhere. Not sure.

**Comment by Teklad** [comment]
There's similar behavior when you extensively use the file search results
widget... Once you clear the results the memory never gets fully
reclaimed... I'm almost certain this is normal QT behavior (it does bother
me though).

My most recent patch to said widget made it capable of reclaiming "most" of
the memory... But I think QT has some internal caching that it does. At
least I hope so.

On Mar 11, 2017 1:36 PM, "JuBan1" <notifications@github.com> wrote:

Right now the QtWebEngine branch leaks a decent amount of memory.

To replicate:

   - Open your favorite system monitor and watch notepadqq-bin's memory
   usage.
   - Open and close tabs a bunch of times.
   - Watch memory grow and not shrink again.

After 60 open/closed tabs memory consumption grew from ~120MiB to ~320MiB
for me. That's around 3MiB per opened tab.

Not sure where it originates from. The CustomQWebView, JsProxy and Editor
objects are properly destroyed when a tab is closed. Valgrind crashes the
process for some reason, so I can't really trace it.

This may not be a memory leak but some lazy block deallocation from
somewhere. Not sure.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/notepadqq/notepadqq/issues/388>, or mute the thread

**Comment by Teklad** [comment]
It could also be a bug regarding how we handle raw editor pointer... But
you would have to test master Notepadqq for the same leak if that were the
case.

**Comment by JuBan1** [comment]
Master doesn't exhibit the same behavior. The destructor of the closed tab's Editor is properly called, too.

**Comment by Teklad** [comment]
In any case, this should resolve itself once we rework the editor assuming
its in there somewhere.  We won't be having to recreate so many widgets
like we're doing now.

Sorry for the segmented replies... At work lol.

On Mar 11, 2017 2:32 PM, "Justin Kinnaird" <jkinnaird1991@gmail.com> wrote:

It could also be a bug regarding how we handle raw editor pointer... But
you would have to test master Notepadqq for the same leak if that were the
case.

**Comment by Teklad** [comment]
Wouldn't that make it an upstream bug?

**Comment by Teklad** [comment]
This would be unfortunate... Long running instances of notepadqq would slowly become unstable as memory got used up... It sounds like a bug in QWebEngine cleanup code... There's really no way to fix it without some really complicated stuff. Lol.

**Comment by JuBan1** [comment]
Yea, we'll have to see about that. Maybe we can go back to recycling Editor instances. Instead of deleting them we put them in a bucket and reuse them. Not new'ing and delete'ing QWebEngine instances might be all that's needed to prevent memory leakage.

**Comment by Teklad** [comment]
Well the proposed modifications to the editor would actually have the same effect... But its mainly annoying that its leaking memory at all when the instancing code is basically the same as when we used QWebKit.

**Comment by Teklad** [comment]
Relevant: https://bugreports.qt.io/browse/QTBUG-58216

**Comment by Teklad** [comment]
OKAY.... so in order to use valgrind with QWebEngine... you have to use the following:
```bash
valgrind --smc-check=all-non-file ./prog --no-sandbox
```

I spent like 2 hours talking to QT devs to figure this out, lol.

**Comment by danieleds** [comment]
> OKAY.... so in order to use valgrind with QWebEngine... you have to use the following:

Oh that's awesome, I remember hitting my head on this some time ago without any solution
