### ISSUE TITLE
QtWebEngine: Imrpove handling of events and data across the Js/C++ boundary

### ISSUE THREAD

**Issue by JuBan1** [notepadqq/notepadqq#390]
With the revert of 03393a5 for webengine-beta we're back at the topic of handling signals and value updates. This should probably be somewhat high up on the TODO list.

**Comment by danieleds** [comment]
For this issue I'd like to forget about the code and discuss what would be the best way to handle this communication.

I'd like to start with a UML diagram of the current status of the architecture.

**Comment by Teklad** [comment]
I'm at work... And I suck with UML diagrams. But the communication
currently works like this.

CppToJS:
- editor invokes jsproxy via sendmsg
- jsproxy emits a signal to communicate with QWebChannel
- QWebChannel catches the signal and invokes received message on the JS
side.
- Depending on the message and data, JavaScript will set a data value in
JsProxy and emits a signal notifying of a data value change.

JsToCpp:
- JS editor event handler hooks to editor.on functions and pushes data as
it changes back to jsproxy via set value and sendEditorEvent...

It might be better to extend sendEditorEvent to where we can pass an
m_value key to modify if its needed.. That would keep from redundant extra
calls to setValue and keep our CPP code clean.

**Comment by danieleds** [comment]
Here are some sequence diagrams about what happening right now, if I've got them correctly:

![c sends a blocking message to javascript](https://cloud.githubusercontent.com/assets/402652/23834345/70c9a332-0755-11e7-9201-109ffaaf4c93.png)
![c sends a command message to javascript](https://cloud.githubusercontent.com/assets/402652/23834346/70cbe494-0755-11e7-82bd-5fbcb5c81f2b.png)
![c wants to get a value from javascript](https://cloud.githubusercontent.com/assets/402652/23834347/70d2fdd8-0755-11e7-9604-7cf74ce03c2c.png)
![javascript sends a message to c](https://cloud.githubusercontent.com/assets/402652/23834348/70d83eb0-0755-11e7-963a-9aa90c6dc66a.png)

The last one is the only one which bugs me. I don't like the fact that the poor app.js is sending values to JsProxy even in case no one will ever care about them.

What about an async API on the c++ side?

**Comment by Teklad** [comment]
Well it mainly sends stuff that's acted upon immediately... technically if we were to fix our signals/slots to actually use the data rather than query Editor every time, everything would go directly where it needs to go without requiring storage.

That's what took so long to get QWebEngine working... we have a lot of places where we query editor data when we shouldn't have to.... OnCursorActivity is a good example of this.

As for the C++ async side... If we could write a wrapper function for runJavascript... similar to your "run on all editors" function... we should be able to have a clean interface for asynchronous calls without breaking the bank.

I mainly just don't want to see runJavascript anywhere at all outside of the editor class, lol.

**Comment by Teklad** [comment]
It would need to work something like this, I think.... correct me if I'm wrong of course.
```cpp
void doAThing()
{
    editor()->sendMessageWithResult(msg, data, callback);
}
void sendMessageWithResult(msg, data, callback)
{
    m_webView->runJavascript("blah blah blah", callback);
}
void doAThingCallback()
{
    //Act on data here
}
```

I know it seems convoluted, but its the best way I can think of without keeping the values synced.

**Comment by Teklad** [comment]
You could of course pass a C++11 expression to keep the callback inline.

**Comment by Teklad** [comment]
Want me to write up a prototype so you can see it in action?  I never got around to doing it before this got merged, lol.

**Comment by danieleds** [comment]
>  technically if we were to fix our signals/slots to actually use the data rather than query Editor every time, everything would go directly where it needs to go without requiring storage.

I agree, but not every data is necessarily bound to an event. I'll explain myself better: right now we have a `cursorPosition` attribute and a `cursorPositionChanged` event. We're interested to the value of the `cursorPosition` attribute only when its value changes, so we can just take the value from the event and we're done (like you say). We can even cache it so that if we need it later, we have it (exactly how we're doing now).

But suppose a new attribute comes up. An attribute of which we're not interested about *when* it changes, but only about its value. It could be an attribute which is consuming in terms of time and/or space. We don't want to update it continuously because we don't care to get notified about when it changes, and because it would cause performance degradation.

We could use QEventLoop to implement a blocking `getMyAttrValue()`, but this causes performance degradation too.

The only alternative is to provide a C++ API to get values asynchronously via callbacks, like in your comment https://github.com/notepadqq/notepadqq/issues/390#issuecomment-285963277.

> I mainly just don't want to see runJavascript anywhere at all outside of the editor class, lol.

that's for sure :P

**Comment by danieleds** [comment]
> Want me to write up a prototype so you can see it in action? I never got around to doing it before this got merged, lol.

Before writing a prototype, do you have some proposal for the methods to introduce?

**Comment by Teklad** [comment]
It might work best if we add callback to all the get[] style functions in Editor... that way it'll keep runJavascript abstract from other parts of Notepadqq... and allow us to do what we need to do.

So say we have.... getSelectedTexts(callback)... we could do this.

```cpp
void MainWindow::doSomethingWithSelectedTexts(all, our, variables)
{
    std::function< void() > callback = [&, const QVariant& data] {//Do something with data in here};
    editor()->getSelectedTexts(callback);
}
```

That's about the cleanest way to do it inline I think... the syntax probably isn't correct, but I haven't made heavy use of C++11 callbacks, so forgive me there, lol.

**Comment by danieleds** [comment]
Yes that makes sense.

Given that asynchrony is "sticky", I think we should also provide an easy way to make those Editor calls blocking, so that complex method can use that (even if async is preferable).

An idea would be... getSelectedTexts(callback) is async, while getSelectedTexts(null) is blocking.

How would you implement the actual communication with Javascript? Can we avoid runJavaScript() and use the existing proxy?

**Comment by Teklad** [comment]
As much as I would love to do that... I've scanned over the docs for QWebChannel numerous times and came up empty when it comes to callbacks... 

We might be able to have JsProxy store a callback when calling sendMsg()... and invoking it once our data is returned.  I haven't tested whether this works or not, but in theory it should.

**Comment by Teklad** [comment]
We'd need to queue callbacks though in the event of fast messages.

**Comment by danieleds** [comment]
Don't worry, let's use runJavaScript() then.

**Comment by Teklad** [comment]
Well it's not the most elegant solution I've ever came up with... but currently, I got it working like this:
```cpp
void MainWindow::on_actionFind_in_Files_triggered()
{
    if (!m_frmSearchReplace) {
        instantiateFrmSearchReplace();
    }
    EditorNS::Callback cb = [&](const QVariant& v) {
        QStringList sel = v.toStringList();
        if (sel.length() > 0 && sel[0].length() > 0) {
            m_frmSearchReplace->setSearchText(sel[0]);
        }
    };
    currentEditor()->getSelectedTexts(cb);

    m_frmSearchReplace->show(frmSearchReplace::TabSearchInFiles);
    m_frmSearchReplace->activateWindow();
}
```

This seems to work really well.  I can see where blocking would be necessary though... such as when you need to retrieve and act on multiple editor values.

**Comment by JuBan1** [comment]
I think that's fine.

**Comment by Teklad** [comment]
It shouldn't be too bad so long as we use events to properly push relevant data.  It's just a couple of extra lines per function, which really isn't all that much... considering how bad it could be.

**Comment by Teklad** [comment]
Just so I don't have a really massive PR from this, I'm going to create my PR in segments.  The first segment is going to focus on improving signal/slot data communication(i.e. send the data we can use directly to the slot so it can be acted upon).  That should take care of a lot of this issue up front.

Here's my plans:
* Separate the events out as much as possible so we only send data that we have to.  As an example, right now we'd have to send 6 pieces of data for refreshEditorUiCursorInfo to function.  Character and line counts can be updated separately from this entity, which will improve performance just a tiny tiny bit.
* Push "CLEAN" events only when the clean state is changed... rather than every time a change event is sent.
* Misc other signals.

The idea is that if we make our editor more state-aware, then Notepadqq as a whole can benefit by executing less code when signals are fired off.... as well as less calls to editor "get" functions in general.
