### ISSUE TITLE
Important: Found something extremely interesting

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#432]
So after a lot of poking around, I ran across this (no KDE dependencies, despite the name):
https://github.com/KDE/syntax-highlighting

This is not a complete editor widget, but is an excellent base to start off of supporting proper highlighting of 250 languages, user defined languages, information for code folding, and themes (i.e. we can port our current themes over with a bit of work).

This gets rid of a lot of the initial pain and agony of writing our own widget from scratch.  Another upside is it appears to depend on the basic QT framework and nothing else (big plus!).  This would accelerate our development time tremendously.

They also have a "codeeditor" example that shows how to implement their code folding properly.  It'll really all boil down to interfacing with it and adding what's missing (keybindings, search, etc.).  

Here's a picture of the highlighting/folding in action using their codeeditor example:
![2017-04-24-221425_662x413_scrot](https://cloud.githubusercontent.com/assets/2869605/25367412/104b6d8a-293b-11e7-9302-32f44fb7a4c6.png)

It's really quite amazing (and very fast).  This will allow us to implement the folding with whatever visuals we see fit, better completion support via ctags and/or other means, etc. Plus a lot of the features we have to endure so much pain implementing via CodeMirror will be a thing of the past.

Other things of importance are the ability to cram customizable keybindings directly into the editor component.  

I believe it's packaged in Ubuntu under libkf5syntaxhighlighting5, but doesn't appear to have any KDE dependencies whatsoever. Distribution would be less of an issue, but providing our own copy just to be safe wouldn't hurt.

I realize it would require throwing away a lot of my work on QWebEngine, but it looks like it would be worth the change.  

I'd like to build the editor component as a separate entity from notepadqq itself until I get it to at least match CodeMirror in its feature set.  This will allow pull requests to continue on notepadqq while allowing the development of the new widget without restrictions or merge issues(on both fronts).

Extension support would also be quite a bit easier to implement considering it's native C++, rather than javascript wizardry.

@danieleds and @JuBan1 I'd like both of your inputs on this.  I realize we moved away from QScintilla due to it being a pain in the arse to work with. This gives us a real opportunity to make something that's much better in that area... as well as beautiful if we give it enough elbow grease.

I've already created a repository named "sourcerer", which I figured was a good code name for an editor component.  I'm currently out of work (lost my job due to some wicked sickness)... so I can dedicate quite a bit of time to this at the moment.

I realize this was a bit of text, so sorry for the long read! :)

**Comment by JuBan1** [comment]
I recall we've had a similar talk about switching CM with some other piece of tech too. Was it Visual Studio Code's system? Can't find the discussion anymore...

Not going to lie, the prospect of getting rid of the WebEngine dependency and CM as well as the JavaScript bindings is intriguing. The move to WebEngine also wasn't what I was hoping for; while you've done a great job, Teklad, the result was still larger and messier than I initially expected. There were just more and more issues popping up as time went on.

As far as I can see this highlighter uses a `QTextDocument` as a base and applies all color formatting using html (note Qt's engine can't display all of html. [Here's](http://doc.qt.io/qt-5/richtext-html-subset.html) a handy reference to what is supported) and Qt's `QSyntaxHighlighter`.

I'm not sure how much it'd take to match CM's feature set. Some things like showing symbols or indent guides might be finnicky. Other stuff like Tabs-to-spaces is a straightforward replacement of JS with some C++ code. For searching it'd probably be a good opportunity to unitify *all* kinds of searches Nqq can perform.

Speed and memory consumption are an unknown but I can't imagine this using more than a friggin' web browser running our text documents.

I don't know if there are any alternatives out there (if we're switching technologies it would be a good idea to see what our options are) but it's an easy sell. It'd more work but the end result will probably be a lot better.

PS:
Instead of making a separate repository, you could also add this as a Qt subproject to Nqq's repository (in a new branch). I feel like that might be a better solution because it'll give great code integration in Qt Creator and make it easier to test changes in either system without having to go back and forth between repos.

**Comment by Teklad** [comment]
My biggest issue is... all the latest changes have made me start thinking about that behemoth Atom editor.  Regardless of how much you kick a browser... at the end of the day, it's still a freaking browser.

Anything we do at this point is just going to be one hacky patch after another.  We can improve the performance now... but the more features we add the slower the JS is gonna get... and we really shouldn't depend on massive CPUs to keep an editor going.

There's a point where we need to just break down and say... "The time is nigh"

**Comment by Teklad** [comment]
The editor component we're using is the lowest common denominator at this point.

**Comment by Teklad** [comment]
Also, @JuBan1 from my research... there's a few other options regarding QT... but one (QCodeEdit) hasn't been updated since Qt4, another (QScintilla) is the one that we trashed while I was MIA from notepadqq, and the others appear very incomplete.  

I'm completely open to other suggestions if you can manage to scrape up some more options from the Google god.

**Comment by Teklad** [comment]
One last thing... my reasoning for a separate repository (can be hosted here on notepadqq's base if so desired)... was due to the fact that in the event(god forbid) we have to rewrite other parts of Notepadqq... it won't be a complete nightmare unhooking our editor component from deeply tied in nonsense.

**Comment by JuBan1** [comment]
Yeaah, there seem to not be that many alternatives. Many known editors just created their own solution. 

I checked Qt Creator's source and they use basically the same stuff: QSyntaxHighlighter on a QTextDocument. So that shows what's possible with it. Might also be a good reference to implement features ourselves.

**Comment by qcerasmus** [comment]
One question remains extensions. If we get rid of the Javascript integration, can we have a serious look at python extensions? Boost has a really nice C++ to Python library found here: http://www.boost.org/doc/libs/1_64_0/libs/python/doc/html/index.html

I want to play around with it a bit more, just would like your thoughts on this?

**Comment by JuBan1** [comment]
The advantage of JavaScript would be that it doesn't require any new dependencies (I think?). The advantage of Python is that it's not JavaScript. So I'm not opposed to it.

Boost is a pretty big dependency - around 150MiB for the package on Arch. But I assume we can get around that by compiling Boost.Python into the executable or something like that. Making Boost a development dependency is fine, making Boost a runtime dependency is a bit murky.

**Comment by Teklad** [comment]
I believe there's also something called PythonQt which provides this same interface... just more Qt-centric.

**Comment by danieleds** [comment]
I would love to get rid of the browser. However, we should face the fact that we're a small team and writing an editor from scratch (or almost from scratch) is... not easy. And not quick.

If we're going to switch to some already existing full-featured editor widget, it should surely be something in active development and with a big community behind.

**Comment by JuBan1** [comment]
> it should surely be something in active development and with a big community behind.

Is there one like that?

Though we *can* just give it a try and see where it goes. The current version of Nqq isn't going anywhere and at worst it's a waste of time. I'd be willing to put some extra hours into it too, just because it sounds like a fun project and I haven't yet done anything like it.

**Comment by Teklad** [comment]
I'm just going to point out that the one I displayed initially is actively developed... by the KDE team.  If that's not a big enough community I'm not sure what is.

With that said, I'm with @JuBan1 on this one... I'm not really concerned about "quick"... I'm concerned about quality.  The level of difficulty is irrelevant to me when it comes to the final result being overall better.  The only full-featured alternative outside of this seems to be QScintilla... and lord forbid we start using that massive steam pile again.

As it stands, I'm not very satisfied with my work on QWebEngine.  As @JuBan1 said, the programming itself isn't the issue... but the way QWebEngine is implemented made what should have been a trivial changeover into a full blown overhaul, and to implement it correctly (completely asynchronous, no middle-man buffer) would mean to turn our code base into a massive mess of lambda expressions.  Even trying to contain it into one location, which I mostly achieved, still left quite a bit to be desired from the team as a whole.

Asynchronous itself is great, but adding it into a program that was originally very synchronous was bound to cause a mess and a lot of problems.  Add to the fact that the QWebEngine API itself seems to be really hit-and-miss based on version (read unstable API)... this sends our version requirements through the roof.

Enter KDE's syntax-highlight project.  Now... creating an editor from bottom to top is a huge task, especially when you consider all the regex, language files, etc. you have to provide.  However, syntax-highlight appears to take care of the two biggest features people enjoy.  

It highlights based on Kate's highlighting format, while still requiring no KDE dependencies from the user.   
 That automatically gives us 250+ languages right out of the gate, sans the untold amounts of extra highlighting files laying dormant around the web.  An added bonus is it adds the base code necessary to easily integrate code folding.  These two features alone are the basis of any editor worth its salt.

That leaves the rest of the smaller features for us to implement.  The only heavy-hitting feature we'll need to take care of at some point is delayed/incremental highlighting.  This is something a lot of popular editors do to keep performance at its best when opening large files.  It's not as painful to implement as it sounds either, lol.  

The general idea is to override rehighlight to where it starts around the view port and highlights that immediately so the user can see the changes.  Then you'll have two iterators that gradually (but quickly) highlight the remainder of the document in the background, giving precious CPU cycles back to the program itself as it runs.  There's only two instances where this method is actually employed.  On document load, and on language change.

On our end of things we can actually avoid highlighting documents that are loaded in the background, such as during reloading of a session.  This will probably require some changes in DocEngine and Sessions in order to do it properly, but should further increase the usability of nqq with better scaling under intensive load.

In all reality its just an illusory trick that editors use to give the sense of the highlighter being a whole lot faster than it actually is, but its a tried and tested method to give the user a good experience.

Aside from all that jazz though, the rest of the features vary from trivial to moderate difficulty... Its very doable.  Sadly even with just the two basic features we're getting close to what we had with CodeMirror. :p

**Comment by danieleds** [comment]
> I'm just going to point out that the one I displayed initially is actively developed... by the KDE team. If that's not a big enough community I'm not sure what is.

It's actively developed but it's *not* an editor :)

What bothers me is not the initial development burst, but the effort required to add future features as they're needed.

I'm not against seeing how it goes though, if you're willing to work on it. How much time do you think you need to come up with a primitive version?

**Comment by Teklad** [comment]
If you mean including converting Notepadqq over to using it as well, then possibly a week or more (Depends on my time constraints). Probably less time than it took to implement QWebEngine up to this point though, lol.

There's obvious features that will take some time to implement.  Proper code completion comes to mind, mainly because I'm not super familiar with ctags and the likes... but preliminary support similar to what CodeMirror provides wouldn't be too bad to implement.

If I can get a primitive version set up then I believe @JuBan1 would be more than okay at hacking away to help with that as well.  

The QWebEngine transition in comparison kept more or less everyone but myself away because its a bloody nightmare to get right without things appearing like hacky evil.

More importantly... I do need to know whether the editor should be developed in a separate repository.  Alternatively, we could create it as a direct Notepadqq library with no actual dependence on anything inside Notepadqq itself.  

Keeping it dependence agnostic helps quite a bit when we need to start improving upon other parts of Notepadqq.  This also gives us some motivation to make sure the API for the editor is **VERY** clear in what its expected to do, rather than being tempted to bind everything together with glue like we're all guilty of at some point. :P

**Comment by danieleds** [comment]
> If you mean including converting Notepadqq over to using it as well

yep, something like that, just to see how it would integrate with our code.

And of course that would be a separate repo, with highly decoupled code.

**Comment by JuBan1** [comment]
Looking over what CM does and what the syntax highlighter + Qt can do, I think we're mostly covered. Initially I thought undo/redo is going to be a problem but QTextDocument has us covered. Find/Replace is fine, scroll-to-cursor is there, etc etc.

Only thing I see is automatic indentation. CM modes do that for us but neither the KDE highlighter nor Qt have this feature built-in. So that's going to be a bit of a hassle implementing ourselves since different languages call for different indentation rules.

**Comment by Teklad** [comment]
@JuBan1 I was thinking about that... it'd probably be best to poke around Kate and see how they interface with their language definitions for it.  Then it'll come down to re-interpreting that data back down to plain Qt.

**Comment by JuBan1** [comment]
Kate's got a [huge mountain of JS code](https://cgit.kde.org/ktexteditor.git/tree/src/script/data/indentation) responsible for indentation. That's called by an Indenter object and applied to the document.

That's probably the way to go if we want to offer users the option to add or modify language support.

**Comment by Teklad** [comment]
In terms of "smart" indentation... I believe that would probably be best.  Even if we don't use Kate's method there are still many other implementations which should work just fine.  Luckily a simple "previous-line" style indentation is extremely easy to achieve... so we can provide that in the beginning and work our way up from there.

syntax-highlighting appears to install a qmake module, so we can continue using the current build system without too many hiccups I think.

Once I figure out how to do the gradual syntax highlighting for language changes/new files... I'm going to see if I can't get it included in upstream.  If not, we can simply provide our own copy of the syntax-highlighting base, which isn't really a huge deal considering we do this with CodeMirror right now anyways.

**Comment by JuBan1** [comment]
So I assume we'll put the QtWebEngine rework on ice for the time being and stick with WebKit until we figure something out?

I'm asking because I'm thinking about polishing up the whole tabs and editors business next, to hopefully get rid of a lot of weird interactions in Nqq. Would be nice to know whether our API will remaing stable for the time being.

**Comment by Teklad** [comment]
I'm okay with keeping QWebKit until I get something workable to replace what we have now.  Just need to confirm with @danieleds on this approach.

**Comment by JuBan1** [comment]
If he's still alive, that is :D

**Comment by JuBan1** [comment]
Since the QtWebKit situation steadily grows worse I've started work on a replacement editor now. [OpenTextEdit](https://github.com/JuBan1/OpenTextEdit) is inspired by the syntax-highlighting project @Teklad posted above and QtCreator's variant.

I've been slaving away at it over the weekend and it's coming along well.

Left side is Nqq, right side is OTE.
![](https://i.imgur.com/lscdWix.png)

The good stuff:
* We can get rid of CM and WebKit for good.
* Much better memory footprint (22MiB vs 100MiB for six open tabs in debug mode).
* Much better startup time (300ms vs 800ms for six open tabs in debug mode).
* Fixed a ton of bugs ("Reload" bug, scroll skipping for large files, etc).
* OTE can do practically *anything* since it directly uses Qt's painting process.


The bad stuff:
* Themes aren't compatible, and CodeMirror's theme files can't easily automatically be converted. Recreating the themes isn't difficult, just time-consuming.
* Syntax highlighting isn't compatible and practically impossible to carry over. That's the biggest issue. I'm looking for a repository of usable syntax definitions but I don't see how we can keep the wealth of available definitions Nqq currently has.
* It might take a bit of work to get some context-sensitive features (like code-folding) to work as nicely in OTE as they do in CM.
* We can't easily inject JavaScript into the Editor anymore as we did with CM.

I've got a Nqq branch where I replaced CM with OTE and it's already working pretty well. The lion share of missing functionality is small stuff.

That leaves one big question @danieleds: how much regression is acceptable when it comes to theming/syntax highlighting? Is it alright to drastically cut down on available options and then gradually re-implement them as they come along? I've trying to find an alternative but haven't had much success yet.

**Comment by Teklad** [comment]
I wouldn't see a problem with that approach @JuBan1.  As long as there is documentation regarding syntax highlighting available I'm sure there are other people who are willing to chip in for all the off-beat languages which will be missing when the new editor is initially released.  As far as themes go, those are a dime in a dozen.  We can recreate some of the most popular themes up front to give the users some options.

Sorry I've been gone for so long.  Work picked back up pretty heavily so I've not had time to do anything besides eat and sleep.  Hoping to find time to do some more hacking on this soon.

**Comment by JuBan1** [comment]
No sweat; it's been a mostly quiet half year altogether.

If you want you can give me [OTE branch](https://github.com/JuBan1/notepadqq/tree/ote-integration) a whirl. CodeMirror's gone and its replacement is shaping up well. It's not done yet (no code folding, only C/C++ and JSON highlighting, only one theme) but I got it to a pretty usable point already.
