### ISSUE TITLE
Opening large files does not work

### ISSUE THREAD

**Issue by ranolfi** [notepadqq/notepadqq#464]
I'm using the v1.0.1 in Arch Linux.

When using the Open command and selecting a large plain text file (1GiB), nothing happens.

The program keeps working normally - it simply appears to ignore the "Open File" request.

**Comment by Teklad** [comment]
This is actually a limitation of CodeMirror.  From what I've gathered upon trying to open a very large file Notepadqq throws a javascript error.

This will eventually be rectified with a new editor component...  The ETA on that is currently unknown, however.

**Comment by marc2377** [comment]
I see. Thanks for clarifying.

**Comment by JuBan1** [comment]
@Teklad do you know if there is a strict limit or if it's just some error that eventually shows up?

We're currently not handling any kind of larger files very gracefully.

**Comment by Teklad** [comment]
@JuBan1 there's no hard limit that I can find posted anywhere in the CodeMirror documentation... but I'm thinking the cutoff limit is somewhere < 500MB...  Its been a while since I've tested the issue but I recall the cutoff being somewhere close to there.

My best guess is due to the way we're handing large files, coupled with the fact that using a browser as the editing widget... the memory usage skyrockets past the Linux kernel's single process maximum possible memory limit.  Since QT has fairly decent recovery from this it would make sense for it to just throw a javascript error rather than crashing the program.

If that's the case it would vary depending on kernel configuration and such.

**Comment by Teklad** [comment]
Or its also possible that there's a hard limit somewhere on how much data QWebKit can handle... I've not tested with the QWebEngine branch.

**Comment by JuBan1** [comment]
From my experiences files of ~1MiB in size take a few seconds to open. Files of ~2MiB take inconveniently long to open. I wouldn't recommend recommend opening files larger than 1MiB. That's also why newer versions warn you when trying to open anything larger.

**Comment by danieleds** [comment]
This has been dramatically improved on the master branch, and will be available in the next release.

Closing for now

**Comment by Mastomaki** [comment]
Using the snap package (v. 1.4.8) opening a 400 MB file worked most of the time. Using the latest master branch version it doesn't work. The app window does not show up but the process is running and using plenty of CPU.

Kubuntu 18.04.
