### ISSUE TITLE
More than one backreference of one capturing group doesn't seem to work

### ISSUE THREAD

**Issue by lepczynski** [notepadqq/notepadqq#465]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using Replace with Regular Expressions, say:
Find: (\w+);
Replace with: \1 = mock(\1.class);
only the first use of \1 works, the second one doesn't : /

**Expected behavior**
Well I hope it could be use it as many times as needed.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Xubuntu 16.04 64bit
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
Notepadqq v1.0.1

**Comment by JuBan1** [comment]
You're right, subsequent groups won't be replaced because our algorithm erroneously stopped after the first instance. Luckily it's a quick fix (808fb12). 

For now you'll only get the fix if you pull the newest version from github and compile it yourself. The packages will eventually be updated but no telling when.
