### ISSUE TITLE
Add "toggle last viewed tab" feature

### ISSUE THREAD

**Issue by s101d1** [notepadqq/notepadqq#469]
Feature request here, I would like to have functionality to toggle last viewed tab, which in Windows  people usually would assign it with Ctrl + Tab key shortcut.

**Comment by Daniel-McCarthy** [comment]
I would be interested in implementing this feature.

I can submit a pull request for this feature, though I feel it may be worth discussing first. 

(1. Notepad++ has a similar feature to this, but it's functionality allows it to also select other tabs than the most recent one. Would a short-cut that purely switches between the current and most recent tab be sufficient?

(2. On the version I have tested (v1.4.8), Ctrl + Tab is set to switch to the adjacent tab to the right. There seems to already be short cuts for switching to adjacent left/right tabs with Ctrl + Page Up/Page Down. But since it is already taken, the toggle feature could potentially use Ctrl + Q. I think this would make practical sense since it is immediately next to Tab.

I would happy to add this if it's something that fits the vision for the project and the details of it are agreed upon.

**Comment by danieleds** [comment]
<kbd>(Shift +) Ctrl + Tab</kbd> is commonly used to switch to adjacent tabs also in web browsers, so I wouldn't change that.

<kbd>Ctrl + Q</kbd> sounds totally fine to me for switching to the last viewed tab. What is your suggestion with respect to the behaviour when multiple views are in use?

**Comment by JuBan1** [comment]
Isn't CTRL+Q often used as a shorthand for quitting? We're not using it as such but there's an argument to be made for swimming with the stream.

**Comment by Daniel-McCarthy** [comment]
Great points. It doesn't seem that Ctrl + T is being used and would potentially be more idiomatic.
I would be happy to set it to Ctrl + T if there are no other problems with that.

As for the functionality when there are multiple views, this is a good question. The functionality in Notepad++ appears to be a combination of the adjacent tab and most recent tab functionality. The Ctrl+Tab shortcut switches to the most recent tab. Ctrl + (Tab(2x)) will instead switch to the adjacent tab.

If the most recent tab is not tracked between multiple views (therefore reset each time you switch views) then it may seem inconsistent and less useful. This feature seems useful to me, though may be a bit more complicated when considering multiple views and windows.

**Comment by JuBan1** [comment]
Fine with me. Shortcuts are easy enough to change in case we get a better idea.

> This feature seems useful to me, though may be a bit more complicated when considering multiple views and windows.

Tracking tab use across multiple views would probably be a good idea. Tracking across sounds overkill to me. Each Window can track its own tab list, but I don't think pressing (Shift+)CTRL+T should move you to another window.

**Comment by danieleds** [comment]
I agree with @JuBan1 . Fine with me too. No need to track it across multiple windows.

**Comment by Daniel-McCarthy** [comment]
My implementations of this have been encountering an issue.

In my stable 1.4.8 installation: When I have two views open, click the editor on the left, and press (Ctrl + N), a new tab opens in the left view. If I click on the right editor and do the same, a new tab opens in the right view.

This behavior does not occur in any builds I have compiled from the current repository master branch. Clicking on the editor in the other view does not change the text at the top, and pressing (Ctrl + N) will continue to occur in the opposite editor.

This is a problem for my current implementation, as it uses the current tabwidget to set the tab index. If this is due to ongoing changes with development I can hold off on this feature.

**Comment by JuBan1** [comment]
Yep; that's a bug. #731 ought to fix it. Perhaps you can give it a whirl. I want to give it some time before I merge it into master in case I find any issues with it.
