### ISSUE TITLE
Window does not take up half the screen when dragged to the screen edge

### ISSUE THREAD

**Issue by scootergrisen** [notepadqq/notepadqq#472]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Blue area should show on half the screen but nothing shows.

**Expected behavior**

Blue aread should show on half the screen and window should be maximized to fill half the screen when mouse button is released.

**Minimal reproduction of the problem with instructions**

Click and hold titlebar with mouse and drag to left or right edge of screen.

**Please tell us about your environment:**

OpenSUSE Thumbleweed
GNOME Version 3.24.2
Linux 4.11.8-2-default x86_64 GNU/Linux
Notepadqq v1.0.1
Qt version 5.9.1.

**Comment by JuBan1** [comment]
Tested it with a fresh install of Tumbleweed with these packages installed and it works fine for me.

**Comment by scootergrisen** [comment]
This seems this happens if one of the tabs have a message like:

> This file is indented with tabs, but your current settings specify to use spaces. [Use tabs] [Ignore]

With multiple tabs open the user might not see this message.

**Comment by JuBan1** [comment]
That explains it. You probably have a relatively small display resolution. These banner messages have a fixed minimum width and half your screen width isn't enough to for it. 

I've fixed that in a patch a while ago but OpenSUSE's repository doesn't contain an up-to-date version of Nqq. That's not their fault though. They decide to stick to official releases and we haven't had one since v1.0.1 which doesn't yet contain the patch.

If you want you can install an up-to-date version yourself (instructions are in the [README](https://github.com/notepadqq/notepadqq/blob/master/README.md)) or wait for a new official version, but will probably take a while.
