### ISSUE TITLE
Problem in syntax highlight

### ISSUE THREAD

**Issue by mmtrt** [notepadqq/notepadqq#547]
when ever I use this '|/-\' OR "|/-\" on script all below text syntax from it have weird highlight behavior its all wrong and its working fine using same script on other apps like gedit, kwrite, vscode.

its normal without it.
https://imgur.com/JSbgGMs

with "|/-\"
https://imgur.com/rXGDJ2J

with '|/-\'
https://imgur.com/VYmRdUK

**Comment by JuBan1** [comment]
The reason for that is because the syntax highlighter sees `\"`  not as the end of a string but instead as a plain quotation mark. So the string started by `"|/...` is only closed with the quotation mark at `testname="`.

Is there a reason why you end the string with `\"` instead of just `"`?

I don't have gedit or kwrite handy but Kate does the same thing as Nqq (https://i.imgur.com/Cnj1aP4.png) and unless bash's syntax doesn't allow for escaping quotation marks I think we're doing it the correct way. But I don't know that much about bash.

**Comment by mmtrt** [comment]
I use it on spinner function for bash script when using ? will destroy the very purpose of spinning / \

even windows softwares do the same behaviour highlighting text, notepad3 and notepad++

full view of spinner function code used on script in nqq

https://imgur.com/a/4h091

**Comment by JuBan1** [comment]
I see. Looks like bash has some differences in how they handle escaping in strings.

I can see two possible workarounds here. The first one is to simply move the `/` somewhere else. The problem exists because of the sequence `\"`, so changing it to `local spinstr="\|-/"` ought to work.

Alternatively you can use an [ANSI C string](http://wiki.bash-hackers.org/syntax/quoting#ansi_c_like_strings) instead. using `local spinstr=$'|/-\\'` should work properly while allowing the syntax highlighter to do its job.
