### ISSUE TITLE
A couple of features request. 

### ISSUE THREAD

**Issue by jazzmale** [notepadqq/notepadqq#687]
Very thankful for the program. I'm submitting a feature request. 

1. To fit Ubuntu styles, please, move a menu to a titlebar and showing under a cursor. 
2. Show the asterisk (or any sign) in a header before a title of a doc when a file is modified but not saved. 

Ubuntu 16.04.4 LTS 
Notepadqq 1.4.2
Qt 5.5.1

**Comment by JuBan1** [comment]
Hey there,

We've had to force disable Ubuntu integration because Ubuntu's Appmenu (the program responsible for handling the titlebar menu) frequently messed up and uses ended up with no menu bar at all. 16.04 is one of the affected versions- so unfortunately you'll probably be better off this way for the time being.

Regarding the second request, I think that's a good idea and I've submitted it as #688.

**Comment by JuBan1** [comment]
#688 is merged. Closing this issue.
