### ISSUE TITLE
Automatic indent doesn't respect selected 'convert tabs to spaces' setting

### ISSUE THREAD

**Issue by srk** [notepadqq/notepadqq#691]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I have 'Replace tabs with spaces' selected under 'Settings/Language', and I press enter at the end of a line of Python source code, I see the expected automatic indentation, but it is composed of 'Tab' characters, NOT spaces.

**Expected behavior**
Automatic indentation would respect the selected 'Tabs to spaces' conversion.

**Minimal reproduction of the problem with instructions**
1.Select the 'Convert tabs to spaces' mode under 'Settings/Language'
2.Open a Python file (.py)
3.Press enter at the end of a long line.

**Please tell us about your environment:**
Ubuntu 16.04LTS, Notepadqq 1.4.8

**Comment by danieleds** [comment]
This might be related to regression #684 (that we already fixed but not published yet).

As a workaround, can you try to explicitly specify the tab/space settings for the Python language, instead of using the "Default" item?

**Comment by srk** [comment]
I tried your most recent suggestion, but the same problem persisted.

**Comment by Teklad** [comment]
If I'm not mistaken until the bugfix gets published you'll likely either have to modify your tab settings manually in the settings file or compile the latest build from source.  This was a fairly obvious oversight on my part, unfortunately.

Try adding this to your Notepadqq.ini:
```ini
python\IndentWithSpaces=true
python\TabSize=4
python\UseDefaultSettings=false
```

**Comment by Teklad** [comment]
@danieleds do you think we could possibly backport this bugfix to the old webkit branch and push it upstream for now?  There's still quite a few things that need to be sorted on master before our next release.

I'm actually going to try and get the single QWebEngineView w/ multiple tabs thing set up before our release, though it might take me about a week or so to sort out the details.  It would actually get rid of a couple of issues altogether (i.e. longer load times, flashing background on tab change, topeditorcontainer rework) rather than requiring workarounds.

**Comment by srk** [comment]
@Teklad That worked, thanks!
