### ISSUE TITLE
Disable native dialogs as a feature enhancement

### ISSUE THREAD

**Issue by RalphShnelvar** [notepadqq/notepadqq#737]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, when opening a file the dialog puts up folders. 

**Expected behavior**

I wish to have the open dialog allow me to input a full or partial path.

**Minimal reproduction of the problem with instructions**

The text above should be sufficient to reproduce the old behavior.

My desired behavior can be achieved by following the advice here: https://askubuntu.com/questions/1059017/how-to-run-a-specific-version-of-qt-with-notepadqq?noredirect=1#comment1735091_1059017 

**Please tell us about your environment:**

Ubuntu 18.04
Notepad 1.4.2
Qt 5.9.5

**Comment by JuBan1** [comment]
So, there's a way to run Nqq with a different Qt version: if you open the launch script (you can see its location using `where notepadqq`) you can uncomment [line 6](https://github.com/notepadqq/notepadqq/blob/master/support_files/launch/notepadqq) and replace the `/opt/Qt/5.10/gcc_64/lib` with the location of any Qt version's lib folder.

However, I don't know if that will make Qt use its own file dialog rather than the native one. 

I wouldn't be opposed to adding a config option to switch between native/qt dialogs as a sort of [hidden setting](https://github.com/notepadqq/notepadqq/issues/301).

**Comment by RalphShnelvar** [comment]
Re: [notepadqq/notepadqq] Disable native dialogs as a feature enhancement (#737)


JuBan1,

Thank you for getting back to me.

I read the "hidden settings" chat you had.

Have you implemented the hidden settings json file yet?  I don't mean "Have you implemented the native dialogs feature yet?".  If you have, it would be nice (critical?) to have a reference to the absolute file name in your settings pull down or in your "?" help.

Ralph



Sunday, July 29, 2018, 12:49:26 PM, you wrote:





So, there's a way to run Nqq with a different Qt version: if you open the launch script (you can see its location using where notepadqq) you can uncomment line 6 and replace the /opt/Qt/5.10/gcc_64/lib with the location of any Qt version's lib folder.
However, I don't know if that will make Qt use its own file dialog rather than the native one.
I wouldn't be opposed to adding a config option to switch between native/qt dialogs as a sort of hidden setting.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





Ralph

**Comment by JuBan1** [comment]
There's no UI for it. But we can have hidden settings that can be changed via Notepadqq's .ini file.

**Comment by RalphShnelvar** [comment]
Re: [notepadqq/notepadqq] Disable native dialogs as a feature enhancement (#737)


JuBan1,

I've been at this a couple of days and I could not tell you where the .ini file is.

All I'm suggesting is that the full path of the .ini file be mentioned somewhere obvious ... like
  the "?"
  Settings pulldown menu, or
  as a tab in Preferences.

Also, are there multiple .ini files? For instance, is there one for a user's home and another for root (--allow-root)?  Right now I think there is only one but I'm not sure.

Ralph



I particularly like the fact that the 

Monday, July 30, 2018, 12:50:10 AM, you wrote:





There's no UI for it. But we can have hidden settings that can be changed via Notepadqq's .ini file.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





Ralph

**Comment by JuBan1** [comment]
The config file should sit in `~/.config/Notepadqq/`. It's not really meant for users to modify it which is why we're not advertising it much - at the moment almost all settings can be set directly from Notepadqq so there is little need.

When you're running Nqq as root the configuration sits in `/root/.config/Notepadqq/`.
