### ISSUE TITLE
How is notepadqq compared to notepad++ in terms of performance?

### ISSUE THREAD

**Issue by waynelapierre** [notepadqq/notepadqq#793]
I am looking for an alternative of notepad++ in Linux. Is notepadqq also based on Scintilla? Is it as fast as notepad++? Also, why notepad++ does not have its Linux version, is it a technical problem? If it is not technically impossible, how can notepadqq compete with notepad++ when notepad++ has its Linux version?

**Comment by JuBan1** [comment]
Notpadqq uses [CodeMirror](https://github.com/codemirror/CodeMirror) instead of Scintilla. It's definitely slower than Notepad++. 

If performance is your main concern you can try [this Notepadqq fork](https://github.com/JuBan1/notepadqq/tree/ote). It's built for speed and low resource-use, but still experimental (so expect a few bugs). It's probably still not as fast as Notepad++ but it comes a lot closer.

You'll have to ask the Notepad++ devs if you want to know why Notepad++ was never brought to Linux, but it's probably that the effort was simply too much and nobody wanted to do it.

**Comment by discarn8** [comment]
DO NOT use Notepadqq. So far, I have lost copious amounts of data in files that are reported as saved by the app - but when closed and then re-opened, the new text is completely missing. VERY angering
