### ISSUE TITLE
Can't find menu for creating macros

### ISSUE THREAD

**Issue by rcoelho6** [notepadqq/notepadqq#833]
There are no option for execute nor create macros on my version of Notepadqq (v1.4.2), is it a bug or a lack of feature?

**Comment by JuBan1** [comment]
Macros have been turned off for a long time by now. Sorry if the screenshot on the README page misled you; it's ooold :)

**Comment by darkdreamingdan** [comment]
Can we update the README maybe? just installed this for this sole purpose and found it doesnt exist.

**Comment by RedactedProfile** [comment]
Notepad++'s macros are the sole reason I have the thing installed via wine. When I saw this thing I got super excited about a native implementation but... but now I'm just kinda sad...

**Comment by Montetobuso** [comment]
Same here, sole reason I installed it. Now I'm removing it again.

**Comment by rubmz** [comment]
Seriously? You HAD macros and REMOVED THEM?

Are you aware of how hard it is to get a sane editor in Ubuntu that can do macros?
Vim - well it's vim, and I am under 80
VS code - needs an extension, then edit their shortcuts FILE. HARD HARD. COMPLEX. THE LINUX WAY...

Why on earth did you remove it? why?

Stupid!

**Comment by buzonjl** [comment]
Hello everyone,  I can create a macro for inserting text automatically using Run menu,  I've used same idea for similar purposes and I have achieved what I have needed, I post my macro for helping you

lxterminal --geometry=50x75 --command="/bin/bash -c 'sleep 0.25s; xdotool key Alt+Tab; xdotool key Ctrl+x; xdotool key backslash; xdotool key b+e+g+i+n; xdotool key braceleft+braceright;  xdotool key Ctrl+v;  xdotool key backslash;  xdotool key e+n+d;  xdotool key braceleft+braceright;   xdotool key Ctrl+f;  sleep 0.25s;xdotool key braceleft+braceright;  xdotool key Enter;  xdotool key Escape;  xdotool key --repeat 3 Shift+F3; xdotool key Right+Left;'

same but I drop the first part sleep 0.25s; xdotool key Alt+Tab;  because it is not needed whet use shortkeys.

lxterminal --geometry=50x75 --command="/bin/bash -c 'xdotool key Ctrl+x; xdotool key backslash; xdotool key b+e+g+i+n; xdotool key braceleft+braceright;  xdotool key Ctrl+v;  xdotool key backslash;  xdotool key e+n+d;  xdotool key braceleft+braceright;   xdotool key Ctrl+f;  sleep 0.25s;xdotool key braceleft+braceright;  xdotool key Enter;  xdotool key Escape;  xdotool key --repeat 3 Shift+F3; xdotool key Right+Left;'

**Comment by guilhermegps** [comment]
Let's support this https://github.com/notepadqq/notepadqq/issues/1062
