### ISSUE TITLE
Context menu not shown for end of line

### ISSUE THREAD

**Issue by lfromanini** [notepadqq/notepadqq#989]
**Describe the bug**
The context menu is not been displayed when right-clicking in the bottom bar over "UNIX / OS X". It should display a context menu to switch between available end lines ("Windows Format", "UNIX / OS X Format" and "Old Mac Format"). This is the default behavior in Notepad++ and should be reproduced on NotepadQQ as well.

**To Reproduce**
1. Go to bottom bar
2. Click on "UNIX / OS X"
3. See error

**Expected behavior**
A context menu with options "Windows Format", "UNIX / OS X Format" and "Old Mac Format" (end of line) should be available, so the user can switch to the appropriated end line.

**Screenshots**

**Environment (please complete the following information):**
 - OS: openSUSE Leap 15.2
 - Installation type: distro packages and editors repo
 - Qt version: 5.12.7
 - Notepadqq version: reproduced on 1.4.0 and 1.4.8

**Additional context**
N/A

**Comment by robertapengelly** [comment]
@lfromanini I think what you want should be a feature request and not a bug report as I don't think what you are after has ever been implemented in the project.

**Comment by lfromanini** [comment]
Perhaps. The idea is to mimic Notepad++.

**Comment by robertapengelly** [comment]
I agree the idea is to mimic it but a bug is technically something that's implemented but doesn't behave the proper way whereas a feature request is a request to add something new which I think your report falls under.  An example of a bug is one I seen within the issues mainly with regards to the latest beta where CTRL+D deletes a line instead of duplicating it.  As far as I'm aware Notepadqq has never had the ability to change the line endings meaning that it's a feature that would be nice to have and it isn't a feature that doesn't behave the way one would expect.

**Comment by lfromanini** [comment]
Yes, I'm aware it's possible to change end of lines in menu, but I think it should also be possible right-clicking the bottom bar, as Notepad++ does. If you think my request fits better as a feature request instead of a bug, feel free to close this ticket and open a feature request in my behalf, or let me know how to do it.

**Comment by robertapengelly** [comment]
@lfromanini When you create a new issue it asks if it's a bug report or feature request (at least for me it does).

**Comment by lfromanini** [comment]
Ticket replaced by #1053.
